version: "3.9"  # optional since v1.27.0
services:
  web:
    build: ./server
    ports:
      - "5001:5001"
  front:
    build: ./client
    ports:
      - "3000:3000"
  redis-server: 
    image: "redis:alpine"
